#!/usr/bin/env python3
"""expand_vpn_pool.py — build a gluetun docker-compose targeting N PIA servers
per region.

Uses gluetun's built-in `format-servers -private-internet-access` as the
source of truth for available named servers (no third-party API scraping).
Writes docker-compose.yml with one service per (region, server), each
pinned via SERVER_NAMES for reproducibility across container restarts.

Examples:
    # Default: 3 servers per region across 7 target APAC regions -> 21 services
    uv run python scripts/expand_vpn_pool.py

    # Every server in every region -> ~36 services (all APAC)
    uv run python scripts/expand_vpn_pool.py --per-region all

    # Different region set
    uv run python scripts/expand_vpn_pool.py --regions Singapore,Macao

    # Build + bring up + verify connectivity
    uv run python scripts/expand_vpn_pool.py --up --test
"""
from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path


DEFAULT_REGIONS = (
    "Singapore",
    "JP Tokyo",
    "Taiwan",
    "Hong Kong",
    "South Korea",
    "Malaysia",
    "Macao",
)

BASE_PORT = 8888


def fetch_gluetun_servers() -> str:
    """Run gluetun's format-servers subcommand and return its stdout."""
    r = subprocess.run(
        [
            "docker", "run", "--rm", "qmcgaw/gluetun",
            "format-servers", "-private-internet-access",
        ],
        capture_output=True, text=True, timeout=120, check=True,
    )
    return r.stdout


def parse_servers(markdown: str) -> list[dict]:
    """Parse gluetun's Markdown table to a list of dicts.

    Each row has: region, hostname, server_name, tcp, udp, port_forward.
    Skips the header row and its separator row; ignores lines that don't
    start with '|' (loose noise tolerance).
    """
    rows: list[dict] = []
    for line in markdown.splitlines():
        if not line.startswith("|"):
            continue
        parts = [p.strip() for p in line.strip().strip("|").split("|")]
        if len(parts) != 6:
            continue
        # Skip the header row (case-insensitive match on the first cell)
        if parts[0].lower() == "region":
            continue
        # Skip the header separator ('| --- | --- | ... |')
        if all(set(p) <= set("-:") and p for p in parts):
            continue
        rows.append({
            "region": parts[0],
            "hostname": parts[1].strip("`"),
            "server_name": parts[2],
            "tcp": "✅" in parts[3],
            "udp": "✅" in parts[4],
            "port_forward": "✅" in parts[5],
        })
    return rows


def pick_servers_per_region(
    servers: list[dict],
    regions: list[str],
    per_region: int | None,
) -> list[dict]:
    """Filter to target regions and pick up to N per region.

    per_region=None means every server in each region. Returns servers
    grouped by region in the order given by `regions`.
    """
    picked: list[dict] = []
    for region in regions:
        region_servers = [s for s in servers if s["region"] == region]
        if per_region is None:
            picked.extend(region_servers)
        else:
            picked.extend(region_servers[:per_region])
    return picked


def render_compose(picked_servers: list[dict]) -> str:
    """Render a docker-compose.yml string for the picked pool."""
    header = """# Auto-generated by scripts/expand_vpn_pool.py — do not edit by hand.
# To regenerate: uv run python scripts/expand_vpn_pool.py [--per-region N]
#
# Each service pins to a specific PIA server via SERVER_NAMES for
# reproducibility. Rerun the script to refresh the server list from
# gluetun's format-servers output.
#
# Usage:
#   docker compose up -d
#   docker compose down
#   uv run python scripts/test_vpn.py

x-vpn-common: &vpn-common
  image: qmcgaw/gluetun:latest
  cap_add:
    - NET_ADMIN
  devices:
    - /dev/net/tun:/dev/net/tun
  healthcheck:
    test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:9999 || exit 1"]
    interval: 30s
    timeout: 10s
    retries: 3
    start_period: 30s
  restart: unless-stopped

x-vpn-env: &vpn-env
  VPN_SERVICE_PROVIDER: private internet access
  VPN_TYPE: openvpn
  OPENVPN_USER: ${PIA_USER}
  OPENVPN_PASSWORD: ${PIA_PASS}
  HTTPPROXY: "on"
  HTTPPROXY_LISTENING_ADDRESS: ":8888"
  HTTPPROXY_STEALTH: "on"

services:
"""
    body: list[str] = []
    for i, s in enumerate(picked_servers, start=1):
        port = BASE_PORT + i - 1
        service = (
            f"\n  vpn-{i}:\n"
            f"    <<: *vpn-common\n"
            f"    container_name: hklii-vpn-{i}\n"
            f"    environment:\n"
            f"      <<: *vpn-env\n"
            f'      SERVER_REGIONS: "{s["region"]}"\n'
            f'      SERVER_NAMES: "{s["server_name"]}"\n'
            f"    ports:\n"
            f'      - "{port}:8888"\n'
        )
        body.append(service.rstrip())
    return header + "\n".join(body) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--per-region", default="3",
        help="Servers per region: integer or 'all' (default 3)",
    )
    parser.add_argument(
        "--regions", default=",".join(DEFAULT_REGIONS),
        help=f"Comma-separated region names (default {','.join(DEFAULT_REGIONS)})",
    )
    parser.add_argument(
        "--output", default="docker-compose.yml",
        help="Compose file path (default docker-compose.yml)",
    )
    parser.add_argument(
        "--up", action="store_true",
        help="Run 'docker compose up -d' after writing the file.",
    )
    parser.add_argument(
        "--test", action="store_true",
        help="Run scripts/test_vpn.py after --up (implies --up).",
    )
    args = parser.parse_args()

    per_region: int | None = (
        None if args.per_region == "all" else int(args.per_region)
    )
    regions = [r.strip() for r in args.regions.split(",")]

    print("Fetching PIA server list via gluetun format-servers ...", flush=True)
    md = fetch_gluetun_servers()
    servers = parse_servers(md)
    print(f"  parsed {len(servers)} total servers", flush=True)

    picked = pick_servers_per_region(servers, regions, per_region)
    per_region_str = "all" if per_region is None else str(per_region)
    print(
        f"Picked {len(picked)} servers = {per_region_str}/region "
        f"× {len(regions)} regions",
        flush=True,
    )
    contributed = {s["region"] for s in picked}
    missing = [r for r in regions if r not in contributed]
    if missing:
        print(f"WARNING: no servers found for regions: {missing}", flush=True)
    counts_by_region: dict[str, int] = {}
    for s in picked:
        counts_by_region[s["region"]] = counts_by_region.get(s["region"], 0) + 1
    for region in regions:
        c = counts_by_region.get(region, 0)
        print(f"  {region}: {c}", flush=True)

    compose = render_compose(picked)
    Path(args.output).write_text(compose)
    print(f"Wrote {args.output} — {len(picked)} services", flush=True)

    if args.up or args.test:
        print("Running: docker compose up -d ...", flush=True)
        subprocess.run(["docker", "compose", "up", "-d"], check=True)
        print("Waiting for containers to report healthy (up to 3 min) ...",
              flush=True)
        # Poll healthcheck via `docker ps`; healthy takes ~60-90s for gluetun.
        import time
        start = time.time()
        target = len(picked)
        while time.time() - start < 180:
            r = subprocess.run(
                ["docker", "ps", "--filter", "name=hklii-vpn-",
                 "--filter", "health=healthy", "--format", "{{.Names}}"],
                capture_output=True, text=True,
            )
            healthy = [ln for ln in r.stdout.splitlines() if ln.strip()]
            if len(healthy) >= target:
                print(f"  {len(healthy)}/{target} healthy", flush=True)
                break
            print(f"  {len(healthy)}/{target} healthy — waiting", flush=True)
            time.sleep(15)
        else:
            r = subprocess.run(
                ["docker", "ps", "--filter", "name=hklii-vpn-",
                 "--format", "{{.Names}}\t{{.Status}}"],
                capture_output=True, text=True,
            )
            print("TIMEOUT: not all containers healthy after 180s. Status:",
                  flush=True)
            print(r.stdout, flush=True)
            return 2

    if args.test:
        print("Running: scripts/test_vpn.py ...", flush=True)
        subprocess.run(
            ["uv", "run", "python", "scripts/test_vpn.py"],
            check=True,
        )
    return 0


if __name__ == "__main__":
    sys.exit(main())
